[package]
name = "ax-display"
version = "0.6.11"
repository = "https://github.com/rcore-os/tgoskits"
edition.workspace = true
authors = ["Shiping Yuan <robert_yuan@pku.edu.com>"]
description = "ArceOS graphics module"
license.workspace = true

[features]
host-test = ["ax-task/host-test"]

[dependencies]
ax-task.workspace = true
ax-lazyinit.workspace = true
ax-hal.workspace = true
log.workspace = true
rdif-display.workspace = true
irq-framework.workspace = true
