target = "x86_64-unknown-none"
env = { AX_IP = "10.0.2.15", AX_GW = "10.0.2.2" }
log = "Warn"
features = [
    "ax-runtime/display",
    "axplat-dyn/efi",
    "ax-driver/nvme",
    "ax-driver/virtio-net",
    "ax-driver/virtio-input",
    "ax-driver/virtio-gpu",
    "ax-driver/virtio-socket",
]
